# Numpy Arrays

[NumPy](https://numpy.org/) is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and a large collection of high-level mathematical functions to operate on these data structures.

NumPy has the benefit of performance since its written in C, and its arrays are stored more efficiently, and offers various mathematical functions to perform operations on these arrays.

## Creating NumPy Arrays

We can create NumPy arrats using NumPy's built in functions.

In [7]:
import numpy as np

# one-dimensional array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

print ("\n")

# two-dimensional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

print ("\n")

# create an array of zeroes
zeroes = np.zeros((2,3))
print(zeroes)

print ("\n")

# create an array of ones
ones = np.ones((3,2))
print(ones)

print ("\n")

#create an array of a specific range
range_arr = np.arange(10)
print(range_arr)


[1 2 3 4 5]


[[1 2 3]
 [4 5 6]]


[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


[0 1 2 3 4 5 6 7 8 9]


Also an array can be created from an existing list.

In [16]:
my_nums = [1, 2, 5, 10]

a = np.array(my_nums, dtype=np.float32)
print(a)

[ 1.  2.  5. 10.]


We can also create NumPy arrays use predetermined values.

In [22]:
# create a 2 by 3 array prefilled with 1
a = np.full((2,3), 1, dtype=np.float16)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


Also, arrays can be created wuth evenly spaced elements using `linspace`.

In [79]:
# create an array of 10 numbers ranging from 1 to 2 evenly spaced
a = np.linspace(1, 2, num=10)
print(a)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


## Array Information

We can also use inbuilt methods to return various information about a NumPy array.

In [80]:
a = np.array([1, 2, 5, 10], dtype=np.float32)

print(f"Dimensions: {a.ndim}")
print(f"Size of Array: {a.size}")
print(f"Memory Used: {a.nbytes}")
print(f"Data Type: {a.dtype}")
print(f"Shape of Array: {a.shape}")

Dimensions: 1
Size of Array: 4
Memory Used: 16
Data Type: float32
Shape of Array: (4,)


## Basic Operations

NumPy arrays support vectorised operations, which are applied element-wise:

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Element-wise addition
print(a + b)

# Element-wise multiplication
print(a * b)

# Scalar multiplication
print(a * 2)


[ 6  8 10 12]
[ 5 12 21 32]
[2 4 6 8]


Also, we can peform an operation on all elements of an array.


In [13]:
a = np.array([1, 2, 3, 4])

a = a + 5
print(a)

[6 7 8 9]


## Indexing and Slicing

NumPy offers various ways to index and slice arrays, similar to Python lists but more powerful.

In [9]:
arr = np.arange(10)

# Get a single element
print(arr[5])

# Slice elements from 2 to 5
print(arr[2:6])

# Conditional indexing
print(arr[arr > 5])


5
[2 3 4 5]
[6 7 8 9]


## Reshaping Arrays

We can also change the orientation of an array using the function `reshape()`.

In [12]:
arr = np.arange(10) 
print ("Original Array:\n", arr)

reshaped_arr = arr.reshape((2, 5))
print("Reshaped Array:\n", reshaped_arr)


Original Array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


We can also transpose an array.

In [82]:
a = np.array([[1,2], [3,4]])
a.T

array([[1, 3],
       [2, 4]])

In [84]:
a = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Arrays can also be flattened.

In [85]:
a = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
a.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Converting Data Type

We can also change the data type of a numpy array.

In [90]:
a = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
print (a.dtype)
print(a)

a = a.astype(np.float16)
print(a.dtype)
print(a)

int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]
float16
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Multiplying Arrays

Arrays can also be multiplied by each other, however its important that they are in the correct shape to be multiplied.

For instance the following will not work because:
- `a` has a dimension of 1,3
- `b` has a dimension of 2,2

so when multiplying `(1,3)*(2,2)` the numbers that are next to each other in this case `3` and `2` must be equal.


In [102]:
a = np.array([[1,2,3]]) 
b = np.array([[1,2],[3,4]])

np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

So, now let's make them the same size.

In [103]:
a = np.array([[1,2]]) 
b = np.array([[1,2],[3,4]])

np.matmul(a,b)

array([[ 7, 10]])

Also, in certain cases you might need to change the order of the multiplication. Consider this case where we have:
- `a` with a size of 2,3
- `b` with a size of 2,2

So, `a*b` will not work since `(2,3)*(2,2)` is not compatible, but `b*a` will work since `(2,2)*(2,3)` is compatible.

In [104]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2],[3,4]])

np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [105]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2],[3,4]])

np.matmul(b,a)

array([[ 9, 12, 15],
       [19, 26, 33]])

Also, a shorthand for multiplication is `@`, and you can also use `np.dot()`.

In [110]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2],[3,4]])

print(b@a)
print(np.dot(b,a))
print(b.dot(a))

[[ 9 12 15]
 [19 26 33]]
[[ 9 12 15]
 [19 26 33]]
[[ 9 12 15]
 [19 26 33]]
