In [31]:
import numpy as np
import random

In [32]:
#1
def generate_temperature(min, max, count):
    return [random.randint(min, max) for _ in range(count)]

In [33]:
#2
temperature_data = np.array([generate_temperature(15, 35, 7) for _ in range(5)])
print(temperature_data)

[[34 27 16 27 34 26 22]
 [31 27 15 23 23 24 31]
 [22 32 16 28 15 27 34]
 [27 23 32 23 27 21 24]
 [23 24 29 35 27 18 26]]


In [34]:
#3
print(temperature_data.shape)

(5, 7)


In [35]:
#4
print(np.mean(temperature_data))

25.514285714285716


In [36]:
#5
print(np.mean(temperature_data, axis=1))

array([26.57142857, 24.85714286, 24.85714286, 25.28571429, 26.        ])

In [38]:
#6
city_b_first_3 = temperature_data[1, :3]
print(city_b_first_3)

[31 27 15]


In [41]:
#7
temperature_f = (temperature_data * 9/5)+32
print(temperature_f.mean())

77.92571428571429


In [45]:
#8
day = np.argmax(temperature_data[3])+1
print (f"Day {day} had the highest temperature of {temperature_data[3][day-1]}")

Day 3 had the highest temperature of 32


In [48]:
#9
all_temps = temperature_data.reshape(-1)

In [57]:
#10
temp_differences = np.max(temperature_data, axis=1) - np.min(temperature_data, axis=1)
print(temp_differences)
print(np.max(temp_differences))

[18 16 19 11 17]
19


In [70]:
#11
weights = np.linspace(0, 1, 7)
weighted_temps =temperature_data * weights

print(weighted_temps)

[[ 0.          4.5         5.33333333 13.5        22.66666667 21.66666667
  22.        ]
 [ 0.          4.5         5.         11.5        15.33333333 20.
  31.        ]
 [ 0.          5.33333333  5.33333333 14.         10.         22.5
  34.        ]
 [ 0.          3.83333333 10.66666667 11.5        18.         17.5
  24.        ]
 [ 0.          4.          9.66666667 17.5        18.         15.
  26.        ]]


In [73]:
heat_index_modifier = np.array([1.1, 1.2, 1.1, 1.3, 1.2, 1.1, 1.2])
total_heat_index = np.dot(temperature_data, heat_index_modifier)
print("Total heat index for each city:", total_heat_index)

Total heat index for each city: [218.3 204.1 205.1 206.7 214.9]
